In [2]:
import numpy as np
#copy
arr=np.array([1,2,3,4,5])
x=arr.copy()
x[0]=89
print(arr)
print(x)

[1 2 3 4 5]
[89  2  3  4  5]


In [3]:
#view
arr1=np.array([6,7,8,9,10,11,12])
y=arr1.view()
y[2]=87
print(arr1)
print(y)

[ 6  7 87  9 10 11 12]
[ 6  7 87  9 10 11 12]


In [5]:
#above you can see that copy owns its data that is why we are not seeing any affect in original array however view does not owns it data since it is the view of original array
arr[2]=4
print(arr)
print(x)

[1 2 4 4 5]
[89  2  3  4  5]


In [7]:
#now made changes in view array
arr1[0]=12
print(arr1)
print(y)

[12  7 87  9 10 11 12]
[12  7 87  9 10 11 12]


In [9]:
#now check whether copy and view owns it data
#numpy as method to check it base
arr2=np.array([1,2,3,4,5,6])
x=arr2.copy()
y=arr2.view()

print(arr2)
#check copy owns it data or not 
print(x.base)

#check view owns it data or not
print(y.base)

[1 2 3 4 5 6]
None
[1 2 3 4 5 6]
