In [1]:
from numpy import random

In [6]:
#generate integer random value
arr=random.randint(100)
print(arr)
print(arr)

68
68


In [7]:
print(arr)

68


In [8]:
print(arr)

68


In [9]:
#generate float random value
arr1=random.rand(100)
print(arr1)

[0.22682296 0.98564975 0.19881859 0.95060654 0.83221161 0.198041
 0.02281943 0.31293551 0.31090913 0.79222355 0.28754981 0.61502934
 0.81608042 0.28395484 0.36094131 0.70069333 0.57718237 0.7236319
 0.62538661 0.5817799  0.11410378 0.65848044 0.53495839 0.41957929
 0.92124635 0.03524632 0.15439012 0.94610491 0.98377279 0.13726323
 0.48481979 0.12686322 0.64411972 0.07582466 0.35391015 0.06814145
 0.61308199 0.65095728 0.36453582 0.28219335 0.40711946 0.22629458
 0.64668977 0.62537629 0.04049372 0.84040964 0.17525713 0.35204843
 0.09544713 0.19663641 0.79330563 0.3069155  0.86773311 0.51180273
 0.97722051 0.76459332 0.91786809 0.81058033 0.37170433 0.24816656
 0.38384247 0.31213874 0.01653207 0.2388526  0.5906274  0.99412254
 0.95685816 0.06790909 0.0046113  0.83659389 0.87197412 0.10200356
 0.52729046 0.98110378 0.12819257 0.45478507 0.14362317 0.25987201
 0.98910523 0.28315205 0.77609981 0.28123064 0.16939929 0.88512994
 0.54854078 0.74738733 0.80475537 0.93393133 0.78413558 0.8664085

In [11]:
print(arr1)

[0.22682296 0.98564975 0.19881859 0.95060654 0.83221161 0.198041
 0.02281943 0.31293551 0.31090913 0.79222355 0.28754981 0.61502934
 0.81608042 0.28395484 0.36094131 0.70069333 0.57718237 0.7236319
 0.62538661 0.5817799  0.11410378 0.65848044 0.53495839 0.41957929
 0.92124635 0.03524632 0.15439012 0.94610491 0.98377279 0.13726323
 0.48481979 0.12686322 0.64411972 0.07582466 0.35391015 0.06814145
 0.61308199 0.65095728 0.36453582 0.28219335 0.40711946 0.22629458
 0.64668977 0.62537629 0.04049372 0.84040964 0.17525713 0.35204843
 0.09544713 0.19663641 0.79330563 0.3069155  0.86773311 0.51180273
 0.97722051 0.76459332 0.91786809 0.81058033 0.37170433 0.24816656
 0.38384247 0.31213874 0.01653207 0.2388526  0.5906274  0.99412254
 0.95685816 0.06790909 0.0046113  0.83659389 0.87197412 0.10200356
 0.52729046 0.98110378 0.12819257 0.45478507 0.14362317 0.25987201
 0.98910523 0.28315205 0.77609981 0.28123064 0.16939929 0.88512994
 0.54854078 0.74738733 0.80475537 0.93393133 0.78413558 0.8664085

In [12]:
#genearte 1-d array
x=random.randint(100,size=(5))
print(x)

[70 84 57 76 98]


In [13]:
print(x)

[70 84 57 76 98]


In [14]:
#generate 2-d array with randomint()
x1=random.randint(100,size=(3,5))
print(x1)

[[30 52 56 81 31]
 [64 47 80 43 27]
 [82 71 16 80 24]]


In [15]:
#generate array with floating number
y=random.rand(100)
print(y)

[0.09457396 0.54405548 0.38925293 0.61512907 0.6765962  0.45950702
 0.3567118  0.53515071 0.80675387 0.89724049 0.33989753 0.00432243
 0.6187209  0.9330908  0.05162072 0.54736378 0.23132043 0.01854246
 0.37855743 0.24016329 0.07143277 0.28827289 0.30259396 0.35648382
 0.00605042 0.67934099 0.09016774 0.47337857 0.91989724 0.77706946
 0.11787879 0.69409998 0.11118206 0.48144956 0.20937576 0.58480425
 0.24082899 0.66389443 0.21753051 0.15617958 0.46624553 0.89381614
 0.05334131 0.80035241 0.89702722 0.6724915  0.9111753  0.96754147
 0.50228453 0.53242353 0.59480044 0.87040344 0.5214871  0.58330844
 0.1962341  0.38294321 0.63020027 0.78949471 0.77283742 0.79448669
 0.52279429 0.38861599 0.021421   0.17511191 0.66414024 0.22825842
 0.80311751 0.86933554 0.25715908 0.8802501  0.50677207 0.63158064
 0.9279436  0.75033765 0.99283781 0.47452893 0.65432869 0.17182279
 0.18778324 0.42974314 0.20049665 0.50204402 0.54807341 0.10383464
 0.96997937 0.76161878 0.19454016 0.72307834 0.06722801 0.2683

In [16]:
#generate 2-d array with floating point number 

y1=random.rand(3,5)
print(y1)

[[0.43449171 0.93144835 0.09075244 0.37705523 0.71806197]
 [0.34762977 0.87027155 0.6952489  0.99040356 0.42417656]
 [0.34089139 0.10905759 0.75298422 0.45781699 0.71074217]]


In [18]:
#choice of random 

z=random.choice([1,2,3,4,5])
print(z)

5


In [19]:
#choice with size
z1=random.choice([1,2,3,4,5],size=(3,5))
print(z1)

[[4 4 2 1 3]
 [5 2 2 4 5]
 [2 2 2 4 1]]
